import Link from 'next/link';
import type { ReactNode } from 'react';
import MotionStoryboardLab from '@/components/lesson/MotionStoryboardLab';
import SimpleDefinition from '@/components/lesson/SimpleDefinition';
import KinematicsDiagnostic from '@/components/lesson/KinematicsDiagnostic';
import styles from './page.module.css';

const nav=[['Home','', '/'],['Block 1','The Intuition & Calculus Spark','/block-1'],['Block 2','Fields, Waves, and Math Tools','/block-2'],['Block 3','The Intermediate Bridge','/block-3'],['Block 4','The Advanced Pillars','/block-4'],['Math Spark','Calculus, ODEs, Linear Algebra','/math-spark'],['Reference','Equations & constants','/reference']] as const;
const miniNav=[['↑ Top of page','#top'],['Picture this','#picture-this'],['Interactive lab','#interactive-lab'],['Build the idea','#build-the-idea'],['What to notice','#what-to-notice'],['Math Spark','#math-spark'],['Now earn the equations','#equations'],['Question answered','#question-answered'],['Real-world challenge','#challenge']] as const;
const equations:[[ReactNode,string],[ReactNode,string],[ReactNode,string],[ReactNode,string],[ReactNode,string],[ReactNode,string]]=[
  [<>v = Δx / Δt</>,'average velocity'],[<>a = Δv / Δt</>,'acceleration'],[<>v = u + at</>,'velocity after time t'],[<>Δx = ut + ½at²</>,'displacement under constant acceleration'],[<>x = x₀ + v₀ₓt</>,'horizontal projectile position'],[<>y = y₀ + v₀ᵧt − ½gt²</>,'vertical projectile position'],
];
function ArrowIcon({chevron=false}:{chevron?:boolean}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={chevron?'m9 5 7 7-7 7':'M4 12h16m-6-6 6 6-6 6'}/></svg>}
function OrbitIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="2"/><ellipse cx="12" cy="12" rx="9" ry="4"/><ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(60 12 12)"/></svg>}
function Equation({children,label}:{children:ReactNode;label:string}){return <span className={styles.equation} role="math" aria-label={label}>{children}</span>}

export default function LessonPage(){return <div className={styles.page} id="top">
  <aside className={styles.sidebar} aria-label="Course navigation"><Link className={styles.brand} href="/">PhySense<small>A field guide to physical law.</small></Link><nav>{nav.map(([label,sub,href])=><Link key={label} href={href} className={label==='Block 1'?styles.active:''} aria-current={label==='Block 1'?'page':undefined}><span className={styles.navMark}>{label==='Block 1'?'01':'·'}</span><span>{label}{sub&&<small>{sub}</small>}</span></Link>)}</nav><div className={styles.learning}><span>Now learning</span><OrbitIcon/><h2>Kinematics</h2><p>Position, velocity, and acceleration — the alphabet of motion.</p><Link href="#picture-this">Continue lesson <ArrowIcon/></Link></div></aside>
  <main className={styles.main}>
    <header className={styles.lessonHeader}><span>Block 1 · Lesson 1.1 · Foundation</span><h1><SimpleDefinition term="Kinematics" definition="The part of physics that describes motion. It tells us where something is, how fast it moves, and how its motion changes—without yet asking what force caused it."/>: <SimpleDefinition term="Motion" definition="When an object changes where it is as time passes. A walking person, a rolling ball, and a flying plane are all in motion."/> in <SimpleDefinition term="1D" definition="One-dimensional motion: movement along one straight line. The object can go forward or backward, like a car on a straight road."/> &amp; <SimpleDefinition term="2D" definition="Two-dimensional motion: movement in two directions at once, such as left–right and up–down. A thrown basketball follows 2D motion."/></h1><p>How <SimpleDefinition term="position" definition="Where an object is compared with a starting point. For example, a car at 20 m is 20 metres from the place we called zero."/>, <SimpleDefinition term="velocity" definition="How fast position changes and in which direction. Positive velocity can mean moving right; negative velocity can mean moving left."/>, and <SimpleDefinition term="acceleration" definition="How velocity changes each second. Acceleration can make something speed up, slow down, or change direction."/> relate.</p></header>
    <section id="picture-this"><h2>Picture this</h2><p>You are riding in a car when the driver presses the brakes. You keep moving forward, but you cover less distance during each passing second.</p><p>Now picture throwing a basketball. It moves forward while gravity pulls it downward, creating one curved path from two simpler motions.</p></section>
    <section id="hold-question"><h2>Hold this question</h2><div className={styles.question}>How can velocity be going down while position is still going up?</div><p className={styles.muted}>Don&apos;t answer yet. You&apos;ll answer it in section 5.</p></section>
    <section id="interactive-lab"><h2>Interactive lab</h2><h3>Motion Storyboard Lab</h3><MotionStoryboardLab/></section>
    <section id="build-the-idea"><h2>Build the idea</h2><h3>From what you see to what you know</h3><ol className={styles.steps}><li><span className={styles.motionTag}>1D motion</span><b>First, choose where zero is and which way is positive.</b><p>On the car&apos;s straight road, call the left edge 0 m. We can call movement to the right positive and movement to the left negative.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Speed and velocity answer different questions.</b><p><strong>Speed</strong> tells you how fast. <strong>Velocity</strong> tells you how fast and which way. A car moving left and a car moving right can have the same speed but different velocities.</p></li><li><span className={styles.motionTag}>1D motion</span><b>A graph turns motion into a visible story.</b><p>On a position–time graph, a rising line means the car is moving right. A flat line means it is stopped. A falling line means it is moving left. A steeper line means a greater speed.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Constant acceleration means velocity changes evenly.</b><p>If GO adds 3 m/s to the velocity every second, the acceleration stays constant. The equations help us predict the car&apos;s position and velocity later.</p></li><li className={styles.dimensionDivider} aria-hidden="true"><span>Now, the second dimension</span></li><li value={5}><span className={`${styles.motionTag} ${styles.twoDTag}`}>2D motion</span><b>A basketball moves in two directions at once.</b><p>It moves horizontally across the court while also moving vertically up and down. Gravity changes the vertical motion, while the horizontal motion continues steadily.</p></li><li><span className={`${styles.motionTag} ${styles.bridgeTag}`}>1D → 2D</span><b>Two-dimensional motion is two 1D stories combined.</b><p>Study the left–right motion and the up–down motion separately. Put them together and you get the basketball&apos;s curved path.</p></li></ol></section>
    <section id="what-to-notice"><h2>What to notice</h2><h3>The physics hiding in plain sight</h3><ul className={styles.notice}><li><span className={styles.motionTag}>1D motion</span><b>Position tells you where the object is.</b><p>If the car is at 30 m, its position is 30 m from the place called zero. Position does not tell you whether the car is moving—it could be driving or parked there.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Speed and velocity are similar, but not the same.</b><p><strong>Speed</strong> has only a size: “10 m/s.” <strong>Velocity</strong> has a size and a direction: “10 m/s to the right.” Two cars can have the same speed while having opposite velocities—one moves right and the other moves left.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Acceleration means velocity is changing.</b><p>An object accelerates when it speeds up, slows down, or changes direction. A car turning around can accelerate even if its speed stays the same, because its direction—and therefore its velocity—changes.</p></li><li className={styles.dimensionDivider} aria-hidden="true"><span>Now, the second dimension</span></li><li><span className={`${styles.motionTag} ${styles.twoDTag}`}>2D motion</span><b>A projectile has two motion stories happening together.</b><p>The basketball moves horizontally across the court while gravity changes its vertical motion. We study left–right and up–down separately, then combine them to understand the curved path.</p></li><li><span className={styles.motionTag}>1D graph</span><b>The slope of a position–time graph shows velocity.</b><p>A rising line means positive velocity, a falling line means negative velocity, and a flat line means zero velocity. The steeper the line, the greater the speed.</p></li></ul></section>
    <section id="math-spark"><h2>Math Spark — the calculus underneath</h2><p className={styles.sectionSubtitle}>Calculus gives us two simple tools: one finds how fast something is changing, and the other adds many tiny changes together.</p><div className={styles.mathIdeas}><article><span>1 · SLOPE</span><h3>Position changes into velocity</h3><p>A <strong>derivative</strong> (the rate of change at one instant) measures the slope of the position–time graph.</p><Equation label="velocity equals the derivative of position with respect to time">v = dx / dt</Equation><p>A steep slope means a large speed. A flat slope means the object is stopped.</p></article><article><span>2 · SLOPE AGAIN</span><h3>Velocity changes into acceleration</h3><p>Take the derivative again. Now the slope of the velocity–time graph tells us the acceleration.</p><Equation label="acceleration equals the derivative of velocity with respect to time">a = dv / dt</Equation><p>A positive slope increases velocity. A negative slope decreases velocity.</p></article><article><span>3 · AREA</span><h3>Acceleration builds velocity</h3><p>An <strong>integral</strong> (a sum of many tiny changes) is the area under a graph. The area under an acceleration–time graph is the change in velocity.</p><Equation label="change in velocity equals the integral of acceleration over time">Δv = ∫ a dt</Equation></article><article><span>4 · AREA AGAIN</span><h3>Velocity builds position</h3><p>The area under a velocity–time graph is the change in position. Motion during every tiny moment adds to the total distance moved in that direction.</p><Equation label="change in position equals the integral of velocity over time">Δx = ∫ v dt</Equation></article></div><div className={styles.derivation}><h3>Unlock the familiar equations</h3><p>Suppose the acceleration <strong>a</strong> stays constant, the starting velocity is <strong>u</strong>, and the motion lasts for <strong>t</strong> seconds.</p><div><article><span>Start with constant acceleration</span><Equation label="acceleration is constant">a = constant</Equation></article><ArrowIcon/><article><span>Add acceleration over time</span><Equation label="velocity equals initial velocity plus acceleration times time">v = u + at</Equation></article><ArrowIcon/><article><span>Add velocity over time</span><Equation label="change in position equals initial velocity times time plus one half acceleration times time squared">Δx = ut + ½at²</Equation></article></div><p><strong>Example:</strong> A car starts from rest, so u = 0. If a = 3 m/s² for 4 s, then v = 12 m/s and Δx = 24 m.</p></div><div className={styles.symbolKey}><h3>What the symbols mean</h3><p><b>x</b> position · <b>Δx</b> change in position · <b>u</b> starting velocity · <b>v</b> velocity now · <b>a</b> acceleration · <b>t</b> time · <b>Δ</b> “change in”</p></div></section>
    <section id="equations"><h2>Now earn the equations</h2><p className={styles.sectionSubtitle}>You&apos;ll see the physics first. The formulas come last.</p><div className={styles.equations}>{equations.map(([formula,meaning],index)=><div key={meaning}><span>{index+1}</span><Equation label={`${meaning} equation`}>{formula}</Equation><p>{meaning}</p></div>)}</div><p className={styles.equationNote}><b>u</b> means &apos;initial velocity&apos;. <b>g</b> is the acceleration due to gravity on Earth: about 9.8 m/s².</p></section>
    <section id="question-answered"><h2>Hold this question — answered</h2><p className={styles.closureSubtitle}>The question from the start of this lesson</p><div className={styles.closureCallout}><p><strong>You asked: How can velocity be going down while position is still going up?</strong></p><p>When the car is slowing down but still moving forward, velocity is decreasing — the velocity line on the graph is falling. But position is still increasing, because the car is still moving forward, just less quickly each second.</p><p>Velocity is how fast position is changing. Even a shrinking speed can add a little more distance. This is called deceleration — not the opposite of motion, but motion that is losing its strength.</p><p>That is the whole idea of Lesson 1.1. Everything else in this page was building up to this one sentence.</p></div></section>
    <section id="challenge"><h2>Real-world challenge</h2><h3>The late yellow light</h3><div className={styles.challengeStory}><span>THE SITUATION</span><p>You are driving at <strong>15 m/s</strong> when a traffic light turns yellow. The stop line is <strong>45 m</strong> ahead.</p><p>You take <strong>0.75 s</strong> to react. After that, the brakes give a constant acceleration of <strong>−6 m/s²</strong>. Can the car stop before the line?</p></div><div className={styles.challengeWork}><h3>Work through the motion in two parts</h3><article><span>PART 1 · REACTION</span><p>Before you press the brake, the velocity stays at 15 m/s.</p><Equation label="reaction distance equals velocity times reaction time">distance = 15 × 0.75 = 11.25 m</Equation></article><article><span>PART 2 · BRAKING</span><p>After the brake is pressed, the velocity falls from 15 m/s to 0 m/s.</p><Equation label="braking time equals velocity divided by acceleration magnitude">time = 15 ÷ 6 = 2.5 s</Equation><Equation label="braking distance equals velocity squared divided by two times acceleration magnitude">distance = 15² ÷ (2 × 6) = 18.75 m</Equation></article><article className={styles.challengeAnswer}><span>ANSWER</span><Equation label="total stopping distance equals reaction distance plus braking distance">11.25 + 18.75 = 30 m</Equation><p><strong>Yes.</strong> The car stops 15 m before the line because 45 m − 30 m = 15 m.</p></article></div><em>Why this matters: safe stopping distance includes both the distance travelled while reacting and the distance travelled while braking.</em><div className={styles.checkYourThinking}><h3>Diagnostic challenge</h3><p>Ten questions test both your answer and the thinking behind it.</p><KinematicsDiagnostic/></div></section>
    <section className={styles.upNext} aria-label="Up next"><Link href="/block-1/1-2"><ArrowIcon/><span><b>Up next · Lesson 1.2 · Forces</b><small>Why motion changes.</small></span><ArrowIcon chevron/></Link></section>
  </main>
  <aside className={styles.miniNav} aria-label="On this page"><span>On this page</span><nav>{miniNav.map(([label,href])=><a href={href} key={href}>{label}</a>)}</nav></aside>
</div>}
