import Link from 'next/link';
import type { ReactNode } from 'react';
import MotionStoryboardLab from '@/components/lesson/MotionStoryboardLab';
import SimpleDefinition from '@/components/lesson/SimpleDefinition';
import styles from './page.module.css';

const nav=[['Home','', '/'],['Block 1','The Intuition & Calculus Spark','/block-1'],['Block 2','Fields, Waves, and Math Tools','/block-2'],['Block 3','The Intermediate Bridge','/block-3'],['Block 4','The Advanced Pillars','/block-4'],['Math Spark','Calculus, ODEs, Linear Algebra','/math-spark'],['Reference','Equations & constants','/reference']] as const;
const miniNav=[['↑ Top of page','#top'],['Picture this','#picture-this'],['Interactive lab','#interactive-lab'],['Build the idea','#build-the-idea'],['Now earn the equations','#equations'],['Math Spark','#math-spark'],['Real-world challenge','#challenge']] as const;
const equations:[[ReactNode,string],[ReactNode,string],[ReactNode,string],[ReactNode,string],[ReactNode,string],[ReactNode,string]]=[
  [<>v = Δx / Δt</>,'average velocity'],[<>a = Δv / Δt</>,'acceleration'],[<>v = u + at</>,'velocity after time t'],[<>Δx = ut + ½at²</>,'displacement under constant acceleration'],[<>x = x₀ + v₀ₓt</>,'horizontal projectile position'],[<>y = y₀ + v₀ᵧt − ½gt²</>,'vertical projectile position'],
];
function ArrowIcon({chevron=false}:{chevron?:boolean}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={chevron?'m9 5 7 7-7 7':'M4 12h16m-6-6 6 6-6 6'}/></svg>}
function OrbitIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="2"/><ellipse cx="12" cy="12" rx="9" ry="4"/><ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(60 12 12)"/></svg>}
function Equation({children,label}:{children:ReactNode;label:string}){return <span className={styles.equation} role="math" aria-label={label}>{children}</span>}

export default function LessonPage(){return <div className={styles.page} id="top">
  <aside className={styles.sidebar} aria-label="Course navigation"><Link className={styles.brand} href="/">PhySense<small>A field guide to physical law.</small></Link><nav>{nav.map(([label,sub,href])=><Link key={label} href={href} className={label==='Block 1'?styles.active:''} aria-current={label==='Block 1'?'page':undefined}><span className={styles.navMark}>{label==='Block 1'?'01':'·'}</span><span>{label}{sub&&<small>{sub}</small>}</span></Link>)}</nav><div className={styles.learning}><span>Now learning</span><OrbitIcon/><h2>Kinematics</h2><p>Position, velocity, and acceleration — the alphabet of motion.</p><Link href="#picture-this">Continue lesson <ArrowIcon/></Link></div></aside>
  <main className={styles.main}>
    <header className={styles.lessonHeader}><span>Block 1 · Lesson 1.1 · Foundation</span><h1><SimpleDefinition term="Kinematics" definition="The part of physics that describes motion. It tells us where something is, how fast it moves, and how its motion changes—without yet asking what force caused it."/>: <SimpleDefinition term="Motion" definition="When an object changes where it is as time passes. A walking person, a rolling ball, and a flying plane are all in motion."/> in <SimpleDefinition term="1D" definition="One-dimensional motion: movement along one straight line. The object can go forward or backward, like a car on a straight road."/> &amp; <SimpleDefinition term="2D" definition="Two-dimensional motion: movement in two directions at once, such as left–right and up–down. A thrown basketball follows 2D motion."/></h1><p>How <SimpleDefinition term="position" definition="Where an object is compared with a starting point. For example, a car at 20 m is 20 metres from the place we called zero."/>, <SimpleDefinition term="velocity" definition="How fast position changes and in which direction. Positive velocity can mean moving right; negative velocity can mean moving left."/>, and <SimpleDefinition term="acceleration" definition="How velocity changes each second. Acceleration can make something speed up, slow down, or change direction."/> relate.</p></header>
    <section id="picture-this"><h2>Picture this</h2><p>You are riding in a car when the driver presses the brakes. You keep moving forward, but you cover less distance during each passing second.</p><p>Now picture throwing a basketball. It moves forward while gravity pulls it downward, creating one curved path from two simpler motions.</p><em>Why this matters: motion becomes easier to understand when you learn to describe what changes—and what does not.</em></section>
    <section id="hold-question"><h2>Hold this question</h2><div className={styles.question}>How can velocity be going down while position is still going up?</div><p className={styles.muted}>Don&apos;t answer yet. You&apos;ll answer it in section 5.</p></section>
    <section id="interactive-lab"><h2>Interactive lab</h2><h3>Motion Storyboard Lab</h3><MotionStoryboardLab/></section>
    <section id="build-the-idea"><h2>Build the idea</h2><h3>From what you see to what you know</h3><ol className={styles.steps}><li><span className={styles.motionTag}>1D motion</span><b>First, choose where zero is and which way is positive.</b><p>On the car&apos;s straight road, call the left edge 0 m. We can call movement to the right positive and movement to the left negative.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Speed and velocity answer different questions.</b><p><strong>Speed</strong> tells you how fast. <strong>Velocity</strong> tells you how fast and which way. A car moving left and a car moving right can have the same speed but different velocities.</p></li><li><span className={styles.motionTag}>1D motion</span><b>A graph turns motion into a visible story.</b><p>On a position–time graph, a rising line means the car is moving right. A flat line means it is stopped. A falling line means it is moving left. A steeper line means a greater speed.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Constant acceleration means velocity changes evenly.</b><p>If GO adds 3 m/s to the velocity every second, the acceleration stays constant. The equations help us predict the car&apos;s position and velocity later.</p></li><li><span className={`${styles.motionTag} ${styles.twoDTag}`}>2D motion</span><b>A basketball moves in two directions at once.</b><p>It moves horizontally across the court while also moving vertically up and down. Gravity changes the vertical motion, while the horizontal motion continues steadily.</p></li><li><span className={`${styles.motionTag} ${styles.bridgeTag}`}>1D → 2D</span><b>Two-dimensional motion is two 1D stories combined.</b><p>Study the left–right motion and the up–down motion separately. Put them together and you get the basketball&apos;s curved path.</p></li></ol><em>Why this matters: once you can read each direction separately, even a curved flight becomes a simple motion story.</em></section>
    <section id="what-to-notice"><h2>What to notice</h2><h3>The physics hiding in plain sight</h3><ul className={styles.notice}><li><span className={styles.motionTag}>1D motion</span><b>Position tells you where the object is.</b><p>If the car is at 30 m, its position is 30 m from the place called zero. Position does not tell you whether the car is moving—it could be driving or parked there.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Speed and velocity are similar, but not the same.</b><p><strong>Speed</strong> has only a size: “10 m/s.” <strong>Velocity</strong> has a size and a direction: “10 m/s to the right.” Two cars can have the same speed while having opposite velocities—one moves right and the other moves left.</p></li><li><span className={styles.motionTag}>1D motion</span><b>Acceleration means velocity is changing.</b><p>An object accelerates when it speeds up, slows down, or changes direction. A car turning around can accelerate even if its speed stays the same, because its direction—and therefore its velocity—changes.</p></li><li><span className={`${styles.motionTag} ${styles.twoDTag}`}>2D motion</span><b>A projectile has two motion stories happening together.</b><p>The basketball moves horizontally across the court while gravity changes its vertical motion. We study left–right and up–down separately, then combine them to understand the curved path.</p></li><li><span className={styles.motionTag}>1D graph</span><b>The slope of a position–time graph shows velocity.</b><p>A rising line means positive velocity, a falling line means negative velocity, and a flat line means zero velocity. The steeper the line, the greater the speed.</p></li></ul><em>Why this matters: these clues let you translate between an object&apos;s motion, its measurements, and the lines on a graph.</em></section>
    <section id="equations"><h2>Now earn the equations</h2><p className={styles.sectionSubtitle}>You&apos;ll see the physics first. The formulas come last.</p><div className={styles.equations}>{equations.map(([formula,meaning],index)=><div key={meaning}><span>{index+1}</span><Equation label={`${meaning} equation`}>{formula}</Equation><p>{meaning}</p></div>)}</div><p className={styles.equationNote}><b>u</b> means &apos;initial velocity&apos;. <b>g</b> is the acceleration due to gravity on Earth: about 9.8 m/s².</p></section>
    <section id="math-spark"><h2>Math Spark — the calculus underneath</h2><details><summary>Open Math Spark</summary><p>Coming in the Math Spark build.</p></details></section>
    <section id="challenge"><h2>Real-world challenge</h2><h3>The late yellow light</h3><div className={styles.challengePlaceholder}>10 diagnostic questions — coming in the Challenge build.</div></section>
    <section className={styles.upNext} aria-label="Up next"><Link href="/block-1/1-2"><ArrowIcon/><span><b>Up next · Lesson 1.2 · Forces</b><small>Why motion changes.</small></span><ArrowIcon chevron/></Link></section>
  </main>
  <aside className={styles.miniNav} aria-label="On this page"><span>On this page</span><nav>{miniNav.map(([label,href])=><a href={href} key={href}>{label}</a>)}</nav></aside>
</div>}
