'use client';

import { useEffect, useRef, useState } from 'react';
import styles from './MotionStoryboardLab.module.css';

type Mode='car'|'ball';
type Sample={timestamp:number;position:number;velocity:number;acceleration:number};
type TimedValue={t:number;value:number};
type Point={x:number;y:number};
const G=9.8;
const ROAD_WIDTH=700,CAR_WIDTH=56,CAR_MARGIN=CAR_WIDTH/2+4,CAR_TRAVEL=ROAD_WIDTH-2*CAR_MARGIN;

function scaledPoints(samples:Sample[],key:'position'|'velocity'|'acceleration',now:number){
  if(!samples.length)return '';
  const visible=samples.filter(sample=>sample.timestamp>=now-6000),values=visible.map(sample=>sample[key]);
  const min=Math.min(...values),max=Math.max(...values),signed=key!=='position',extent=Math.max(Math.abs(min),Math.abs(max),.1),span=Math.max(max-min,.1);
  return visible.map(sample=>{const x=660-(now-sample.timestamp)/6000*624,y=signed?110-sample[key]/extent*82:192-(sample[key]-min)/span*164;return `${x},${y}`}).join(' ');
}

function CombinedGraph({samples,now,onClear}:{samples:Sample[];now:number;onClear:()=>void}){
  return <div className={styles.graphBlock}><button type="button" className={styles.clearGraph} aria-label="Clear graph data" onClick={onClear}>Clear graph</button><svg className={styles.combinedGraph} viewBox="0 0 700 220" role="img" aria-label="Position, velocity, and acceleration over time"><g className={styles.legend}><circle className={styles.positionDot} cx="44" cy="18" r="4"/><text x="53" y="22">Position</text><circle className={styles.velocityDot} cx="130" cy="18" r="4"/><text x="139" y="22">Velocity</text><circle className={styles.accelerationDot} cx="218" cy="18" r="4"/><text x="227" y="22">Acceleration</text></g><path className={styles.axes} d="M36 32v160h630M36 110h630"/><text className={styles.axisText} x="630" y="211">last 6 s</text>{samples.length>1&&<><polyline className={styles.positionLine} points={scaledPoints(samples,'position',now)}/><polyline className={styles.velocityLine} points={scaledPoints(samples,'velocity',now)}/><polyline className={styles.accelerationLine} points={scaledPoints(samples,'acceleration',now)}/></>}</svg></div>;
}

function Readout({label,value}:{label:string;value:string}){return <div><span>{label}</span><b aria-live="polite">{value}</b></div>}

export default function MotionStoryboardLab(){
  const [mode,setMode]=useState<Mode>('car'),[position,setPosition]=useState(0),[velocity,setVelocity]=useState(0),[acceleration,setAcceleration]=useState(0),[samples,setSamples]=useState<Sample[]>([]),[graphNow,setGraphNow]=useState(0);
  const [speed,setSpeed]=useState(18),[angle,setAngle]=useState(47),[ball,setBall]=useState<Point>({x:0,y:0}),[trail,setTrail]=useState<Point[]>([]),[launched,setLaunched]=useState(false);
  const roadRef=useRef<SVGSVGElement>(null),dragging=useRef(false),carSampling=useRef(false),positionRef=useRef(0),carFrame=useRef(0),launchFrame=useRef(0),tabRefs=useRef<(HTMLButtonElement|null)[]>([]),reduced=useRef(false);
  const positionWindow=useRef<TimedValue[]>([]),velocityWindow=useRef<TimedValue[]>([]),smoothedVelocity=useRef(0),smoothedAcceleration=useRef(0),lastMove=useRef(0);
  const radians=angle*Math.PI/180,vx=speed*Math.cos(radians),vy=speed*Math.sin(radians),airTime=speed>0?2*vy/G:0,range=vx*airTime,peakHeight=vy*vy/(2*G);

  useEffect(()=>{reduced.current=window.matchMedia('(prefers-reduced-motion: reduce)').matches;return()=>{cancelAnimationFrame(carFrame.current);cancelAnimationFrame(launchFrame.current)}},[]);
  const stopAnimations=()=>{cancelAnimationFrame(carFrame.current);cancelAnimationFrame(launchFrame.current);dragging.current=false;carSampling.current=false};
  const resetBall=()=>{cancelAnimationFrame(launchFrame.current);setBall({x:0,y:0});setTrail([]);setLaunched(false)};
  const reset=()=>{stopAnimations();if(mode==='car'){positionRef.current=0;setPosition(0);setVelocity(0);setAcceleration(0);setSamples([]);setGraphNow(0);positionWindow.current=[];velocityWindow.current=[];smoothedVelocity.current=0;smoothedAcceleration.current=0;lastMove.current=0}else resetBall()};
  const switchMode=(next:Mode)=>{if(next===mode)return;stopAnimations();if(next==='ball')resetBall();else resetBall();setMode(next)};
  const readCarPosition=(clientX:number)=>{const rect=roadRef.current?.getBoundingClientRect();if(!rect)return positionRef.current;const svgX=(clientX-rect.left)/rect.width*ROAD_WIDTH;return Math.max(0,Math.min(100,(svgX-CAR_MARGIN)/CAR_TRAVEL*100))};
  const sampleCar=(now:number)=>{if(!carSampling.current)return;positionWindow.current.push({t:now,value:positionRef.current});positionWindow.current=positionWindow.current.filter(sample=>sample.t>=now-150);const oldPosition=positionWindow.current.find(sample=>sample.t<=now-120)??positionWindow.current[0],rawVelocity=now-oldPosition.t>=105?(positionRef.current-oldPosition.value)/.12:smoothedVelocity.current,nextVelocity=.25*rawVelocity+.75*smoothedVelocity.current;velocityWindow.current.push({t:now,value:nextVelocity});velocityWindow.current=velocityWindow.current.filter(sample=>sample.t>=now-150);const oldVelocity=velocityWindow.current.find(sample=>sample.t<=now-120)??velocityWindow.current[0],rawAcceleration=now-oldVelocity.t>=105?(nextVelocity-oldVelocity.value)/.12:smoothedAcceleration.current;let nextAcceleration=.25*rawAcceleration+.75*smoothedAcceleration.current,settledVelocity=nextVelocity;if(now-lastMove.current>200){settledVelocity=0;nextAcceleration=0;carSampling.current=false}smoothedVelocity.current=settledVelocity;smoothedAcceleration.current=nextAcceleration;const graphVelocity=Math.round(settledVelocity*100)/100,graphAcceleration=Math.round(nextAcceleration*100)/100;setVelocity(settledVelocity);setAcceleration(nextAcceleration);setGraphNow(now);setSamples(current=>[...current,{timestamp:now,position:positionRef.current,velocity:graphVelocity,acceleration:graphAcceleration}].filter(sample=>sample.timestamp>=now-6000));if(carSampling.current)carFrame.current=requestAnimationFrame(sampleCar)};
  const beginSampling=(now:number)=>{if(carSampling.current)return;carSampling.current=true;positionWindow.current=[{t:now,value:positionRef.current}];velocityWindow.current=[{t:now,value:smoothedVelocity.current}];carFrame.current=requestAnimationFrame(sampleCar)};
  const startDrag=(event:React.PointerEvent<SVGSVGElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);dragging.current=true;const next=readCarPosition(event.clientX),now=performance.now();positionRef.current=next;setPosition(next);lastMove.current=now;beginSampling(now)};
  const moveCar=(event:React.PointerEvent<SVGSVGElement>)=>{if(!dragging.current)return;const next=readCarPosition(event.clientX),now=performance.now();if(Math.abs(next-positionRef.current)>.001)lastMove.current=now;positionRef.current=next;setPosition(next);beginSampling(now)};
  const stopCar=()=>{if(!dragging.current)return;dragging.current=false};
  const launch=()=>{cancelAnimationFrame(launchFrame.current);setLaunched(true);setBall({x:0,y:0});const fullTrail=Array.from({length:61},(_,i)=>{const t=airTime*i/60;return{x:vx*t,y:Math.max(0,vy*t-.5*G*t*t)}});if(reduced.current){setTrail(fullTrail);setBall({x:range/2,y:peakHeight});requestAnimationFrame(()=>setBall({x:range,y:0}));return}setTrail([{x:0,y:0}]);const start=performance.now();const animate=(now:number)=>{const t=Math.min(airTime,(now-start)/1000),point={x:vx*t,y:Math.max(0,vy*t-.5*G*t*t)};setBall(point);setTrail(current=>[...current,point].slice(-240));if(t<airTime)launchFrame.current=requestAnimationFrame(animate)};launchFrame.current=requestAnimationFrame(animate)};
  const courtPoint=(point:Point)=>({x:50+(range?point.x/range:0)*600,y:280-(peakHeight?point.y/peakHeight:0)*210}),ballPoint=courtPoint(ball),trailPoints=trail.map(courtPoint).map(point=>`${point.x},${point.y}`).join(' ');
  const changeTabByKey=(event:React.KeyboardEvent<HTMLDivElement>)=>{if(event.key!=='ArrowLeft'&&event.key!=='ArrowRight')return;event.preventDefault();const next:Mode=event.key==='ArrowRight'?'ball':'car';switchMode(next);tabRefs.current[next==='car'?0:1]?.focus()};

  return <div className={styles.lab} role="region" aria-label="Motion Storyboard Lab">
    <div className={styles.toolbar} role="tablist" aria-label="Lab modes" onKeyDown={changeTabByKey}><button ref={node=>{tabRefs.current[0]=node}} role="tab" aria-selected={mode==='car'} className={mode==='car'?styles.active:''} onClick={()=>switchMode('car')}>Car on a road</button><button ref={node=>{tabRefs.current[1]=node}} role="tab" aria-selected={mode==='ball'} className={mode==='ball'?styles.active:''} onClick={()=>switchMode('ball')}>Basketball launch</button><button className={styles.reset} type="button" onClick={reset}>Reset</button></div>
    {mode==='car'?<div role="tabpanel"><p className={styles.tryThis} role="note"><b>Try this:</b> Drag the car slowly to the right. Watch the position graph grow while the velocity graph stays low. Then drag faster — see how the velocity changes.<em>Question to hold: Can position be increasing while velocity is decreasing?</em></p><svg ref={roadRef} className={styles.road} viewBox="0 0 700 140" role="img" aria-label="A draggable car on a horizontal road" onPointerDown={startDrag} onPointerMove={moveCar} onPointerUp={stopCar} onPointerCancel={stopCar}><rect className={styles.asphalt} x="0" y="82" width="700" height="58"/><path d="M0 111h700"/><g className={styles.car} transform={`translate(${CAR_MARGIN+position/100*CAR_TRAVEL} 0)`}><rect x="-27" y="66" width="54" height="25" rx="5"/><path d="m-16 66 10-15h21l13 15"/><circle cx="-17" cy="94" r="8"/><circle cx="18" cy="94" r="8"/></g><text x="18" y="25">0 m</text><text x="640" y="25">100 m</text></svg><CombinedGraph samples={samples} now={graphNow} onClear={()=>setSamples([])}/><div className={styles.readouts}><Readout label="Position" value={`${position.toFixed(1)} m`}/><Readout label="Velocity" value={`${velocity.toFixed(1)} m/s`}/><Readout label="Acceleration" value={`${acceleration.toFixed(1)} m/s²`}/></div></div>:<div role="tabpanel"><p className={styles.tryThis} role="note"><b>Try this:</b> Set the launch speed to 18 m/s and the angle to 47°. Launch the ball. Now try a steeper angle — the ball goes higher but travels less far. Why?<em>Question to hold: Does the horizontal speed change during the flight?</em></p><svg className={styles.court} viewBox="0 0 700 320" role="img" aria-label="A basketball following a projectile path across a court"><path className={styles.ground} d="M20 280h660"/>{trailPoints&&<polyline className={styles.trail} points={trailPoints}/>}<g className={styles.ball} transform={`translate(${ballPoint.x} ${ballPoint.y})`}><circle r="13"/><path d="M-13 0h26M0-13c-7 7-7 19 0 26M0-13c7 7 7 19 0 26"/></g></svg><div className={styles.controls}><label><span>Launch speed <output>{speed.toFixed(1)} m/s</output></span><input type="range" min="0" max="30" step="0.5" value={speed} onChange={event=>setSpeed(Number(event.target.value))}/></label><label><span>Launch angle <output>{angle}°</output></span><input type="range" min="0" max="90" step="1" value={angle} onChange={event=>setAngle(Number(event.target.value))}/></label></div><button className={styles.launch} type="button" aria-label="Launch ball" onClick={launch}>Launch</button><div className={`${styles.readouts} ${styles.ballReadouts}`}><Readout label="Air time" value={launched?`${airTime.toFixed(2)} s`:'—'}/><Readout label="Range" value={launched?`${range.toFixed(1)} m`:'—'}/><Readout label="Horizontal speed" value={launched?`${vx.toFixed(1)} m/s`:'—'}/><Readout label="Vertical speed" value={launched?`${vy.toFixed(1)} m/s`:'—'}/><Readout label="Peak height" value={launched?`${peakHeight.toFixed(1)} m`:'—'}/></div></div>}
    <p className={styles.hint}>{mode==='car'?'Drag the car to see how position, velocity, and acceleration relate.':'Change the speed and angle, then launch. Watch the arc.'}</p>
  </div>;
}
